# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: postgresql-db
spec:
 serviceName: postgresql-db-service
 replicas: 2
 selector:
  matchLabels:
   app: postgresql-db
  
 template:
  metadata:
   labels:
    app: postgresql-db
  spec:
   volumes:
    - name: postgres-pv-storage
      persistentVolumeClaim:
       claimName: task-pv-claim
   containers:
   - name: postgresql-db
     image: postgres:latest
     volumeMounts:
     - name: postgres-pv-storage
       mountPath: /data
     env:
     - name: POSTGRES_PASSWORD
       value: testpassword
     - name: PGDATA
       value: /data/pgdata
